image: circleci/android:api-24

stages:
    - check
    - package

before_script:
    - export GRADLE_USER_HOME=$(pwd)/.gradle

cache:
    paths:
        - .gradle/wrapper
        - .gradle/caches

Run all checks:
    stage: check
    script:
        - ./gradlew check

Build APK (debug):
    stage: package
    script:
        - ./gradlew assembleDebug
        - cp app/build/outputs/apk/debug/app-debug.apk .
    artifacts:
        paths:
            - app-debug.apk
        expose_as: Debug APK
