image: circleci/android:api-24-node

stages:
    - check
    - build

before_script:
    - export GRADLE_USER_HOME=$(pwd)/.gradle

.gradle:
    cache:
        paths:
            - .gradle/wrapper
            - .gradle/caches

Run Gradle checks:
    extends: .gradle
    stage: check
    script:
        - ./gradlew check
    cache:
        paths:
            - .gradle/wrapper
            - .gradle/caches

Test Firestore rules:
    stage: check
    cache:
        paths:
            - node_modules
    script:
        - curl -sL firebase.tools | bash
        - yarn install
        - yarn test

Build APK (debug):
    extends: .gradle
    stage: build
    script:
        - ./gradlew assembleDebug
        - cp app/build/outputs/apk/debug/app-debug.apk .
    artifacts:
        paths:
            - app-debug.apk
        expose_as: Debug APK

Publish to Google Play:
    extends: .gradle
    stage: build
    only:
        - master
    script:
        - cp "$PLAY_STORE_JSON_FILE" app/play_store_credentials.json
        - echo "$KEYSTORE_FILE_BASE64" | base64 -d > app/.keystore
        - echo -n "$KEYSTORE_PASSWORD" | sha256sum
        - sha1sum app/.keystore
        - ./gradlew publishRelease --no-daemon

Deploy Firebase changes:
    stage: build
    only:
        - master
    script:
        - curl -sL firebase.tools | bash
        - firebase deploy
