image: circleci/android:api-29-node

stages:
    - check
    - build

before_script:
    - export GRADLE_USER_HOME=$(pwd)/.gradle

.gradle:
    cache:
        paths:
            - .gradle/wrapper
            - .gradle/caches

Run Gradle checks:
    extends: .gradle
    stage: check
    script:
        - ./gradlew check
    cache:
        paths:
            - .gradle/wrapper
            - .gradle/caches

Test Firestore rules:
    stage: check
    cache:
        paths:
            - node_modules
    script:
        - curl -sL firebase.tools | bash
        - yarn install
        - yarn test

Publish to Google Play:
    extends: .gradle
    stage: build
    only:
        - master
        - tags
    script:
        - cp "$PLAY_STORE_JSON_FILE" app/play_store_credentials.json
        - echo "$KEYSTORE_FILE_BASE64" | base64 -d > app/.keystore
        - export APP_VERSION_NAME="${CI_COMMIT_TAG:-dev-$CI_COMMIT_SHORT_SHA}"
        - ./gradlew publishRelease --no-daemon

Deploy Firebase changes:
    stage: build
    only:
        - master
    script:
        - curl -sL firebase.tools | bash
        - firebase deploy

Run Firestore migrations:
    stage: build
    image: 14.5.0-alpine3.12
    cache:
        paths:
            - node_modules
    only:
        - master
    script:
        - yarn install
        - yarn tsc
        - yarn fireway migrate --path firebase-build/migrations
