image: circleci/android:api-30-node

stages:
    - check
    - build

before_script:
    - export GRADLE_USER_HOME=$(pwd)/.gradle

.gradle:
    image: alvrme/alpine-android:android-30-jdk11
    cache:
        paths:
            - .gradle/wrapper
            - .gradle/caches

.nodejs:
    image: timbru31/java-node:11-jdk-erbium
    cache:
        paths:
            - node_modules

Unit tests:
    extends: .gradle
    stage: check
    script:
        - ./gradlew --no-daemon --parallel testDebugUnitTest

Lint:
    extends: .gradle
    stage: check
    script:
        - ./gradlew --no-daemon --parallel testDebugUnitTest

Test Firestore rules:
    extends: .nodejs
    stage: check
    script:
        - yarn install
        - yarn test

Publish to Google Play:
    extends: .gradle
    stage: build
    only:
        - master
        - tags
    script:
        - cp "$PLAY_STORE_JSON_FILE" app/play_store_credentials.json
        - echo "$KEYSTORE_FILE_BASE64" | base64 -d > app/.keystore
        - export APP_VERSION_NAME="${CI_COMMIT_TAG:-dev-$CI_COMMIT_SHORT_SHA}"
        - ./gradlew publishRelease --no-daemon

Deploy Firebase changes:
    extends: .nodejs
    stage: build
    only:
        - master
    script:
        - yarn install
        - yarn firebase deploy

Run Firestore migrations:
    extends: .nodejs
    stage: build
    only:
        - master
    script:
        - yarn install
        - yarn tsc
        - yarn fireway migrate --path firebase-build/migrations
