image: circleci/android:api-24

stages:
    - check
    - build

before_script:
    - export GRADLE_USER_HOME=$(pwd)/.gradle

cache:
    paths:
        - .gradle/wrapper
        - .gradle/caches

Run all checks:
    stage: check
    script:
        - ./gradlew check

Build APK (debug):
    stage: build
    script:
        - ./gradlew assembleDebug
        - cp app/build/outputs/apk/debug/app-debug.apk .
    artifacts:
        paths:
            - app-debug.apk
        expose_as: Debug APK

Deploy Firebase changes:
    image: devillex/docker-firebase:slim
    stage: build
    only:
        - master
    script:
        - firebase deploy
