image: circleci/android:api-30-node

include:
    - template: Security/Secret-Detection.gitlab-ci.yml

stages:
    - test
    - build
    - publish

before_script:
    - export GRADLE_USER_HOME=$(pwd)/.gradle

.gradle:
    image: alvrme/alpine-android:android-30-jdk11
    cache:
        paths:
            - .gradle/wrapper
            - .gradle/caches

.nodejs:
    image: timbru31/java-node:11-jdk-erbium
    cache:
        paths:
            - node_modules

Unit tests:
    extends: .gradle
    stage: test
    script:
        - ./gradlew --no-daemon --parallel testDebugUnitTest

Lint:
    extends: .gradle
    stage: test
    script:
        - ./gradlew --no-daemon --parallel testDebugUnitTest

Test Firestore rules:
    extends: .nodejs
    stage: test
    script:
        - yarn install
        - yarn test

Build release bundle:
    extends: .gradle
    stage: build
    only:
        - master
        - tags
    script:
        - echo "$KEYSTORE_FILE_BASE64" | base64 -d > app/.keystore
        - "export SUPPLY_VERSION_CODE=$((100 + $CI_PIPELINE_IID)) && echo $SUPPLY_VERSION_CODE"
        - export SUPPLY_VERSION_NAME="${CI_COMMIT_TAG:-dev-$CI_COMMIT_SHORT_SHA}"
        - ./gradlew bundleRelease
        - mv app/build/outputs/bundle/release/app-release.aab .
    artifacts:
        paths:
            - app-release.aab


Publish to Google Play:
    image: ruby:2.7.2-alpine3.12
    stage: publish
    only:
        - master
        - tags
    script:
        - apk add build-base
        - cp "$PLAY_STORE_JSON_FILE" fastlane/play_store_credentials.json
        - bundle install -j $(nproc)
        - bundle exec fastlane deploy

Deploy Firebase changes:
    extends: .nodejs
    stage: publish
    only:
        - master
    script:
        - yarn install
        - yarn firebase deploy

Run Firestore migrations:
    extends: .nodejs
    stage: publish
    only:
        - master
    script:
        - yarn install
        - yarn tsc
        - yarn fireway migrate --path firebase-build/migrations
